name: Python DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --------------------------------------------------------
  # JOB 1 : SAST (Analyse Statique du code source Python)
  # --------------------------------------------------------
  sast-scan:
    name: Analyse Statique CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Initialisation de CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python

      - name: Exécution de l'analyse CodeQL
        uses: github/codeql-action/analyze@v4

  # --------------------------------------------------------
  # JOB 2 : SCA (Analyse des dépendances Python)
  # --------------------------------------------------------
  sca-scan:
    name: Analyse SCA Trivy
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Scan du fichier requirements.txt
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0' # On ne bloque pas le pipeline pour le TP
          ignore-unfixed: true
          vuln-type: 'library'
          severity: 'HIGH,CRITICAL'

  # --------------------------------------------------------
  # JOB 3 : DAST (Analyse Dynamique de l'application Flask)
  # --------------------------------------------------------
  dast-scan:
    name: Analyse Dynamique OWASP ZAP
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Démarrage de l'application Flask en arrière-plan
        run: python app.py &
        
      - name: Attente de l'initialisation du serveur
        run: sleep 5

      - name: Scan OWASP ZAP
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:5000'
          fail_action: false
