name: Python DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --------------------------------------------------------
  # JOB 1 : SAST (Analyse Statique du code source Python)
  # --------------------------------------------------------
  sast-scan:
    name: Analyse Statique CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Initialisation de CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python

      - name: Exécution de l'analyse CodeQL
        uses: github/codeql-action/analyze@v4

  # --------------------------------------------------------
  # JOB 2 : SCA (Analyse des dépendances Python)
  # --------------------------------------------------------
  sca-scan:
    name: Analyse SCA Trivy
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Scan du fichier requirements.txt
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0' # On ne bloque pas le pipeline pour le TP
          ignore-unfixed: true
          vuln-type: 'library'
          severity: 'HIGH,CRITICAL'

  # --------------------------------------------------------
  # JOB 3 : DAST (Analyse Dynamique Authentifiée)
  # --------------------------------------------------------
  dast-scan:
    name: Analyse Dynamique ZAP avec Privilèges
    runs-on: ubuntu-latest
    permissions:
      issues: write # Autorise ZAP à créer un ticket d'incident
      contents: read # Autorise la lecture du code
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation et Démarrage
        run: |
          pip install -r requirements.txt
          python app.py &
          sleep 5
# --- AJOUT DE CETTE ÉTAPE POUR CORRIGER L'ERREUR DE PERMISSION ---
      - name: Accorder les permissions d'écriture pour le conteneur ZAP
        run: chmod 777 $GITHUB_WORKSPACE
        
      - name: Scan OWASP ZAP (Authentifié de manière sécurisée)
        uses: zaproxy/action-baseline@v0.14.0
        # On utilise les variables d'environnement prévues par ZAP pour éviter les problèmes d'espaces
        env:
          ZAP_AUTH_HEADER: "Authorization"
          ZAP_AUTH_HEADER_VALUE: "${{ secrets.ZAP_AUTH_TOKEN }}"
          ZAP_AUTH_HEADER_SITE: "http://localhost:5000"
        with:
          target: 'http://localhost:5000'
          fail_action: false
